version: '3'

services:
  marzban:
    container_name: marzban
    image: gozargah/marzban:latest
    ports:
      - 443:443
      - 80:80
    env_file:
      - .env
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.18.0.2
    volumes:
      - ./certbot/conf:/etc/letsencrypt:ro # certificates
      - ./xray:/usr/local/share/xray # geo-files
      - ./xray/xray:/usr/local/bin/xray # xray core
      - ./marzban/xray_config.json:/code/xray_config.json # xray core config
      - ./marzban/db.sqlite3:/code/db.sqlite3 # users DB
      - ./marzban/templates:/code/templates # templates for sub and pages
      - ./marzban/singbox.py:/code/app/subscription/singbox.py #signs 
  # nginx:
  #     image: nginx:latest
  #     container_name: nginx
  #     restart: unless-stopped
  #     ports:
  #     - 443:443
  #     - 80:80
  #     env_file:
  #     - .env
  #     logging:
  #       driver: 'json-file'
  #       options:
  #         max-size: '10m'
  #     networks:
  #       default:
  #         ipv4_address: 172.18.0.3
  #     volumes:
  #       - ./nginx/error.log:/var/log/nginx/error.log
  #       - ./nginx/access.log:/var/log/nginx/access.log
  #       - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #       - ./certbot/conf:/etc/letsencrypt
  #       - ./certbot/www:/var/www/certbot
  #     command: [nginx-debug, "-g", "daemon off;"]


networks:
  default:
    name: proxy
    ipam:
        config:
          - subnet: 172.18.0.0/16
            gateway: 172.18.0.1